// <auto-generated />
using System;
using InsuranceWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceWeb.Migrations.Auth
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260331140953_AddUniquePasswordHash")]
    partial class AddUniquePasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceWeb.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("permission_name");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("resource");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            Action = "View",
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(60),
                            PermissionName = "View Dashboard",
                            Resource = "Dashboard"
                        },
                        new
                        {
                            PermissionId = 2,
                            Action = "Report",
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(66),
                            PermissionName = "Generate Reports",
                            Resource = "Dashboard"
                        },
                        new
                        {
                            PermissionId = 3,
                            Action = "View",
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(68),
                            PermissionName = "View Delay Predictions",
                            Resource = "DelayPredictions"
                        },
                        new
                        {
                            PermissionId = 4,
                            Action = "Modify",
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(69),
                            PermissionName = "Modify Delay Settings",
                            Resource = "DelayPredictions"
                        },
                        new
                        {
                            PermissionId = 5,
                            Action = "View",
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(70),
                            PermissionName = "View Cost Predictions",
                            Resource = "CostPredictions"
                        },
                        new
                        {
                            PermissionId = 6,
                            Action = "Modify",
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(72),
                            PermissionName = "Modify Cost Settings",
                            Resource = "CostPredictions"
                        },
                        new
                        {
                            PermissionId = 7,
                            Action = "View",
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(73),
                            PermissionName = "View Fraud Predictions",
                            Resource = "FraudPredictions"
                        },
                        new
                        {
                            PermissionId = 8,
                            Action = "Modify",
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(74),
                            PermissionName = "Modify Fraud Settings",
                            Resource = "FraudPredictions"
                        },
                        new
                        {
                            PermissionId = 9,
                            Action = "Investigate",
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(75),
                            PermissionName = "Investigate Fraud",
                            Resource = "FraudPredictions"
                        },
                        new
                        {
                            PermissionId = 10,
                            Action = "View",
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(76),
                            PermissionName = "View Forecast",
                            Resource = "Forecast"
                        },
                        new
                        {
                            PermissionId = 11,
                            Action = "Modify",
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(77),
                            PermissionName = "Modify Forecast",
                            Resource = "Forecast"
                        },
                        new
                        {
                            PermissionId = 12,
                            Action = "ManageUsers",
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(78),
                            PermissionName = "Manage Users",
                            Resource = "Admin"
                        },
                        new
                        {
                            PermissionId = 13,
                            Action = "ViewLogs",
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(79),
                            PermissionName = "View Audit Logs",
                            Resource = "Admin"
                        },
                        new
                        {
                            PermissionId = 14,
                            Action = "Upload",
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(80),
                            PermissionName = "Upload Data",
                            Resource = "DataUpload"
                        });
                });

            modelBuilder.Entity("InsuranceWeb.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 541, DateTimeKind.Utc).AddTicks(9973),
                            Description = "Full access to all features, data upload, and reporting",
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 541, DateTimeKind.Utc).AddTicks(9980),
                            Description = "Read-only access to dashboards and reports",
                            RoleName = "Business Analyst"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 541, DateTimeKind.Utc).AddTicks(9981),
                            Description = "User and account management, platform administration",
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("InsuranceWeb.Models.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_permission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("role_permissions");

                    b.HasData(
                        new
                        {
                            RolePermissionId = 1,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(105),
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 2,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(108),
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 3,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(109),
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 4,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(110),
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 5,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(111),
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 6,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(112),
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 7,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(113),
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 8,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(114),
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 9,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(115),
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 10,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(116),
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 11,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(117),
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 12,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(118),
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 13,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(119),
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 14,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(119),
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 15,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(120),
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 16,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(121),
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 17,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(122),
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 18,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(123),
                            PermissionId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 19,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(124),
                            PermissionId = 12,
                            RoleId = 3
                        },
                        new
                        {
                            RolePermissionId = 20,
                            CreatedAt = new DateTime(2026, 3, 31, 14, 9, 52, 542, DateTimeKind.Utc).AddTicks(125),
                            PermissionId = 13,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("InsuranceWeb.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("password_hash");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PasswordHash")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("InsuranceWeb.Models.RolePermission", b =>
                {
                    b.HasOne("InsuranceWeb.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceWeb.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InsuranceWeb.Models.User", b =>
                {
                    b.HasOne("InsuranceWeb.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InsuranceWeb.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("InsuranceWeb.Models.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
