// <auto-generated />
using System;
using InsuranceWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceWeb.Migrations.Auth
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260401175823_AddAuditLog")]
    partial class AddAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceWeb.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("int")
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit")
                        .HasColumnName("is_resolved");

                    b.Property<string>("LoginAttempted")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("login_attempted");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("PreviousIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("previous_ip");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("severity");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("InsuranceWeb.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("permission_name");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("resource");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            Action = "View",
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2798),
                            PermissionName = "View Dashboard",
                            Resource = "Dashboard"
                        },
                        new
                        {
                            PermissionId = 2,
                            Action = "Report",
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2803),
                            PermissionName = "Generate Reports",
                            Resource = "Dashboard"
                        },
                        new
                        {
                            PermissionId = 3,
                            Action = "View",
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2804),
                            PermissionName = "View Delay Predictions",
                            Resource = "DelayPredictions"
                        },
                        new
                        {
                            PermissionId = 4,
                            Action = "Modify",
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2805),
                            PermissionName = "Modify Delay Settings",
                            Resource = "DelayPredictions"
                        },
                        new
                        {
                            PermissionId = 5,
                            Action = "View",
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2806),
                            PermissionName = "View Cost Predictions",
                            Resource = "CostPredictions"
                        },
                        new
                        {
                            PermissionId = 6,
                            Action = "Modify",
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2808),
                            PermissionName = "Modify Cost Settings",
                            Resource = "CostPredictions"
                        },
                        new
                        {
                            PermissionId = 7,
                            Action = "View",
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2809),
                            PermissionName = "View Fraud Predictions",
                            Resource = "FraudPredictions"
                        },
                        new
                        {
                            PermissionId = 8,
                            Action = "Modify",
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2810),
                            PermissionName = "Modify Fraud Settings",
                            Resource = "FraudPredictions"
                        },
                        new
                        {
                            PermissionId = 9,
                            Action = "Investigate",
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2811),
                            PermissionName = "Investigate Fraud",
                            Resource = "FraudPredictions"
                        },
                        new
                        {
                            PermissionId = 10,
                            Action = "View",
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2813),
                            PermissionName = "View Forecast",
                            Resource = "Forecast"
                        },
                        new
                        {
                            PermissionId = 11,
                            Action = "Modify",
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2814),
                            PermissionName = "Modify Forecast",
                            Resource = "Forecast"
                        },
                        new
                        {
                            PermissionId = 12,
                            Action = "ManageUsers",
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2815),
                            PermissionName = "Manage Users",
                            Resource = "Admin"
                        },
                        new
                        {
                            PermissionId = 13,
                            Action = "ViewLogs",
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2816),
                            PermissionName = "View Audit Logs",
                            Resource = "Admin"
                        },
                        new
                        {
                            PermissionId = 14,
                            Action = "Upload",
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2817),
                            PermissionName = "Upload Data",
                            Resource = "DataUpload"
                        });
                });

            modelBuilder.Entity("InsuranceWeb.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2727),
                            Description = "Full access to all features, data upload, and reporting",
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Read-only access to dashboards and reports",
                            RoleName = "Business Analyst"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2731),
                            Description = "User and account management, platform administration",
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("InsuranceWeb.Models.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_permission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("role_permissions");

                    b.HasData(
                        new
                        {
                            RolePermissionId = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2841),
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2843),
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2844),
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2845),
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 5,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2846),
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 6,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2847),
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 7,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2848),
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 8,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2849),
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 9,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2849),
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 10,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2851),
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 11,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2852),
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 12,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2852),
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 13,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2853),
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 14,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2854),
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 15,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2855),
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 16,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2855),
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 17,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2856),
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 18,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2857),
                            PermissionId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            RolePermissionId = 19,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2858),
                            PermissionId = 12,
                            RoleId = 3
                        },
                        new
                        {
                            RolePermissionId = 20,
                            CreatedAt = new DateTime(2026, 4, 1, 17, 58, 23, 375, DateTimeKind.Utc).AddTicks(2859),
                            PermissionId = 13,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("InsuranceWeb.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("password_hash");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PasswordHash")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("InsuranceWeb.Models.AuditLog", b =>
                {
                    b.HasOne("InsuranceWeb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceWeb.Models.RolePermission", b =>
                {
                    b.HasOne("InsuranceWeb.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceWeb.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InsuranceWeb.Models.User", b =>
                {
                    b.HasOne("InsuranceWeb.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InsuranceWeb.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("InsuranceWeb.Models.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
