using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Text;

namespace InsuranceWeb.Controllers
{
    [Authorize(Roles = "Business Analyst")]
    public class ReportingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Export(string reportTitle, string reportContent, string exportFormat)
        {
            var title   = string.IsNullOrWhiteSpace(reportTitle)   ? "Strategic Report" : reportTitle.Trim();
            var content = string.IsNullOrWhiteSpace(reportContent) ? ""                 : reportContent;
            var date    = DateTime.Now.ToString("dd/MM/yyyy HH:mm");
            var author  = User.FindFirst(System.Security.Claims.ClaimTypes.Name)?.Value
                       ?? User.FindFirst("Login")?.Value
                       ?? "Analyst";

            if (exportFormat == "txt")
            {
                var separator = new string('=', Math.Max(title.Length, 40));
                var text = new StringBuilder();
                text.AppendLine(title);
                text.AppendLine(separator);
                text.AppendLine();
                text.AppendLine($"Author   : {author}");
                text.AppendLine($"Date     : {date}");
                text.AppendLine($"Platform : Insurance BI – Claims Intelligence");
                text.AppendLine();
                text.AppendLine(separator);
                text.AppendLine();
                text.Append(content);

                var fileName = $"report_{DateTime.Now:yyyyMMdd_HHmm}.txt";
                return File(Encoding.UTF8.GetBytes(text.ToString()), "text/plain; charset=utf-8", fileName);
            }
            else
            {
                var html     = BuildHtmlReport(title, content, author, date);
                var fileName = $"report_{DateTime.Now:yyyyMMdd_HHmm}.html";
                return File(Encoding.UTF8.GetBytes(html), "text/html; charset=utf-8", fileName);
            }
        }

        private static string BuildHtmlReport(string title, string content, string author, string date)
        {
            var safeTitle   = WebUtility.HtmlEncode(title);
            var safeAuthor  = WebUtility.HtmlEncode(author);
            var safeContent = WebUtility.HtmlEncode(content)
                                        .Replace("\r\n", "\n")
                                        .Replace("\n", "<br>");

            return $@"<!DOCTYPE html>
<html lang=""en"">
<head>
  <meta charset=""utf-8""/>
  <meta name=""viewport"" content=""width=device-width, initial-scale=1""/>
  <title>{safeTitle}</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; }}
    body {{
      font-family: 'Segoe UI', Arial, sans-serif;
      color: #1e293b;
      background: #fff;
      margin: 0;
      padding: 2.5cm 3cm;
      line-height: 1.75;
    }}
    header {{
      border-bottom: 3px solid #1d4ed8;
      padding-bottom: 1rem;
      margin-bottom: 1.5rem;
    }}
    header h1 {{
      margin: 0 0 .4rem;
      font-size: 1.8rem;
      color: #1d4ed8;
    }}
    .meta {{
      font-size: .82rem;
      color: #64748b;
      display: flex;
      gap: 1.5rem;
      flex-wrap: wrap;
    }}
    .meta span strong {{ color: #334155; }}
    .badge {{
      display: inline-block;
      background: #dbeafe;
      color: #1d4ed8;
      border-radius: 4px;
      padding: .1rem .55rem;
      font-size: .78rem;
      font-weight: 600;
      letter-spacing: .04em;
    }}
    .body-content {{
      margin-top: 1.5rem;
      font-size: .97rem;
    }}
    footer {{
      margin-top: 3rem;
      padding-top: .75rem;
      border-top: 1px solid #e2e8f0;
      font-size: .75rem;
      color: #94a3b8;
      text-align: center;
    }}
    @media print {{
      body {{ padding: 1.5cm 2cm; }}
    }}
  </style>
</head>
<body>
  <header>
    <h1>{safeTitle}</h1>
    <div class=""meta"">
      <span><strong>Author:</strong> {safeAuthor}</span>
      <span><strong>Date:</strong> {date}</span>
      <span><span class=""badge"">Insurance BI Platform</span></span>
    </div>
  </header>

  <div class=""body-content"">{safeContent}</div>

  <footer>Generated by Insurance BI – Claims Intelligence Platform &nbsp;|&nbsp; {date}</footer>
</body>
</html>";
        }
    }
}
